security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
                    id: fos_user.user_provider.username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            form_login:
               provider: fos_userbundle
               csrf_token_generator: security.csrf.token_manager
            guard:
                authenticators:
                    - 'token_authenticator'
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$,       roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/login,    roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/doc,      roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/user,     roles: ROLE_USER }
        - { path: ^/api/*,        roles: ROLE_USER }
        - { path: ^/resetting,    roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/,       roles: ROLE_ADMIN }

